config:
  ipfs: https://ipfs.network.thegraph.com

postgres:
  db: graph-node
  host: postgres-postgresql
  user: postgres
replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits: #TODO: Tune requests/limits during acceptance tests
    cpu: 100m
    memory: 200Mi

role: "query-node"

monitoring:
  enabled: true

ingress:
  enabled: true
  hosts:
  - graph-gcp.dm3ch.net
  tls:
  - hosts:
    - graph-gcp.dm3ch.net
    secretName: query-node-https
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

ingressWebsocket:
  enabled: true
  hosts:
  - graph-ws.dm3ch.net
  tls:
  - hosts:
    - graph-ws.dm3ch.net
    secretName: query-node-ws-https
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
